[[constraint]]
  name = "github.com/hairyhenderson/toml"
  branch = "support-map-interface-keys"

[[override]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.3"
